version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_INITDB_SQL: /docker-entrypoint-initdb.d/initdb.sql
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
