"""refresh db1

Revision ID: 2c1b5ad82283
Revises: a22233c25f3a
Create Date: 2023-02-01 00:19:48.909396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1b5ad82283'
down_revision = 'a22233c25f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'description')
    # ### end Alembic commands ###
