"""refresh db1

Revision ID: a17ff7d6e5af
Revises: 44174314f560
Create Date: 2023-02-01 19:56:34.661209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17ff7d6e5af'
down_revision = '44174314f560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('content', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'content')
    # ### end Alembic commands ###
