
name: Development Compose CI

on:
  [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: Run server
      run: docker-compose -f docker-compose.dev.yml up --build -d
permissions: 
  contents: write