
name: Development Compose CI

on:
  [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: Run server
      run: docker-compose up --build -d
    - name: Run tests
      run: docker exec mangochat_web_1 /bin/bash -c "python -m pytest tests/tests.py"
  deploy:
    runs-on: self-hosted
    needs: run
    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: Deploy
      run: docker-compose up --build -d

permissions: 
  contents: write
