
name: Development Compose CI

on:
  [push]

jobs:
  run:
    runs-on: 4g

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: Copy .env
      run: cp /home/faglo/env/env ./.env
    - name: Run server
      run: docker-compose up --build -d
permissions: 
  contents: write
